  <hr>
    <footer>
    <a href="https://bianca89.atlassian.net/?continue=https%3A%2F%2Fbianca89.atlassian.net%2Fwelcome%2Fsoftware%3FprojectId%3D10033&atlOrigin=eyJpIjoiYzg5ZTQ0ZDA2N2FjNDRjYjkwNTVmNzgxYzIzNmFjMTEiLCJwIjoiamlyYS1zb2Z0d2FyZSJ9" target="_blank">Jira</a>
    <a href= https://github.com/106512035/g05repositorypart2.git
     <a href="mailto:support@shopnest.com">Contact Us</a>


    </footer>